#!/bin/bash

set -ex

# Copy Spack Config
SPACK=$SNAP_COMMON

#if [ ! -d "$SPACK" ]; then
#    mkdir $SPACK
#    chmod 755 $SPACK
#fi

# Copy over Spack configs
cp $SNAP/etc/spack/defaults/config.yaml $SPACK/config.yaml
cp $SNAP/etc/spack/defaults/modules.yaml $SPACK/modules.yaml

# Update to use $SNAP_USER_COMMON
sed -i 's@root: \$spack/opt/spack@root: '"$SPACK"'@g' $SPACK/config.yaml
sed -i 's@\$spack@'"$SPACK"'@g' $SPACK/config.yaml
sed -i 's@\$spack@'"$SPACK"'@g' $SPACK/modules.yaml
